"""Project scaffolding templates and rendering utilities."""

from dataclasses import dataclass
from pathlib import Path
import re
from typing import Literal

from jinja2 import Template

from eitohforge_cli.template_parts.application_templates import APPLICATION_FILE_TEMPLATES
from eitohforge_cli.template_parts.cache_templates import CACHE_FILE_TEMPLATES
from eitohforge_cli.template_parts.core_templates import CORE_FILE_TEMPLATES
from eitohforge_cli.template_parts.external_api_templates import EXTERNAL_API_FILE_TEMPLATES
from eitohforge_cli.template_parts.jobs_templates import JOBS_FILE_TEMPLATES
from eitohforge_cli.template_parts.messaging_templates import MESSAGING_FILE_TEMPLATES
from eitohforge_cli.template_parts.notification_templates import NOTIFICATION_FILE_TEMPLATES
from eitohforge_cli.template_parts.search_templates import SEARCH_FILE_TEMPLATES
from eitohforge_cli.template_parts.socket_templates import SOCKET_FILE_TEMPLATES
from eitohforge_cli.template_parts.storage_templates import STORAGE_FILE_TEMPLATES
from eitohforge_cli.template_parts.webhook_templates import WEBHOOK_FILE_TEMPLATES


@dataclass(frozen=True)
class TemplateContext:
    """Context values used for template rendering."""

    project_name: str
    package_name: str
    forge_profile: str = "standard"


PROJECT_FILE_TEMPLATES: dict[str, str] = {
    "README.md": """# {{ project_name }}

Generated by EitohForge.
""",
    "pyproject.toml": """[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[project]
name = "{{ package_name }}"
version = "0.1.0"
description = "Generated backend service by EitohForge."
requires-python = ">=3.12"
dependencies = [
  "alembic>=1.16.0",
  "fastapi>=0.116.0",
  "psycopg[binary]>=3.2.0",
  "sqlalchemy>=2.0.0",
  "uvicorn>=0.32.0",
  "pydantic-settings>=2.10.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
""",
    ".env.example": """EITOHFORGE_APP_NAME={{ project_name }}
EITOHFORGE_APP_ENV=local
EITOHFORGE_LOG_LEVEL=INFO
EITOHFORGE_RUNTIME_PUBLIC_BASE_URL=
EITOHFORGE_RUNTIME_CORS_ALLOW_ORIGINS=
EITOHFORGE_RUNTIME_CORS_ALLOW_CREDENTIALS=false
EITOHFORGE_RUNTIME_TRUST_FORWARDED_HEADERS=false
EITOHFORGE_RUNTIME_DEFAULT_BIND_HOST=127.0.0.1
EITOHFORGE_RUNTIME_DEFAULT_BIND_PORT=8000
EITOHFORGE_RUNTIME_ENFORCE_HTTPS_REDIRECT=false
{% if forge_profile == "minimal" %}
# forge_profile=minimal — enable features below as needed (see docs/guides/forge-profiles.md)
EITOHFORGE_AUTH_JWT_ENABLED=true
EITOHFORGE_REALTIME_ENABLED=false
EITOHFORGE_REALTIME_REQUIRE_ACCESS_JWT=true
{% else %}
EITOHFORGE_AUTH_JWT_ENABLED=true
EITOHFORGE_REALTIME_ENABLED=true
EITOHFORGE_REALTIME_REQUIRE_ACCESS_JWT=true
{% endif %}
EITOHFORGE_DB_DRIVER=postgresql+psycopg
EITOHFORGE_DB_HOST=localhost
EITOHFORGE_DB_PORT=5432
EITOHFORGE_DB_USERNAME=postgres
EITOHFORGE_DB_PASSWORD=postgres
EITOHFORGE_DB_NAME={{ package_name }}
EITOHFORGE_DB_ANALYTICS_ENABLED=false
EITOHFORGE_DB_ANALYTICS_DRIVER=postgresql+psycopg
EITOHFORGE_DB_ANALYTICS_HOST=localhost
EITOHFORGE_DB_ANALYTICS_PORT=5432
EITOHFORGE_DB_ANALYTICS_USERNAME=postgres
EITOHFORGE_DB_ANALYTICS_PASSWORD=postgres
EITOHFORGE_DB_ANALYTICS_NAME={{ package_name }}_analytics
EITOHFORGE_DB_SEARCH_ENABLED=false
EITOHFORGE_DB_SEARCH_DRIVER=postgresql+psycopg
EITOHFORGE_DB_SEARCH_HOST=localhost
EITOHFORGE_DB_SEARCH_PORT=5432
EITOHFORGE_DB_SEARCH_USERNAME=postgres
EITOHFORGE_DB_SEARCH_PASSWORD=postgres
EITOHFORGE_DB_SEARCH_NAME={{ package_name }}_search
EITOHFORGE_AUTH_JWT_SECRET=replace-with-32-plus-char-secret
EITOHFORGE_AUTH_ACCESS_TOKEN_MINUTES=15
EITOHFORGE_AUTH_REFRESH_TOKEN_DAYS=7
EITOHFORGE_CACHE_PROVIDER=redis
EITOHFORGE_CACHE_REDIS_URL=redis://localhost:6379/0
EITOHFORGE_CACHE_DEFAULT_TTL_SECONDS=60
{% if forge_profile == "minimal" %}
EITOHFORGE_RATE_LIMIT_ENABLED=false
{% else %}
EITOHFORGE_RATE_LIMIT_ENABLED=true
{% endif %}
EITOHFORGE_RATE_LIMIT_MAX_REQUESTS=120
EITOHFORGE_RATE_LIMIT_WINDOW_SECONDS=60
EITOHFORGE_RATE_LIMIT_KEY_HEADERS=x-actor-id,x-forwarded-for,x-real-ip
EITOHFORGE_RATE_LIMIT_SCOPE_PATH_PREFIX=
{% if forge_profile == "minimal" %}
EITOHFORGE_IDEMPOTENCY_ENABLED=false
{% else %}
EITOHFORGE_IDEMPOTENCY_ENABLED=true
{% endif %}
EITOHFORGE_IDEMPOTENCY_HEADER_NAME=idempotency-key
EITOHFORGE_IDEMPOTENCY_TTL_SECONDS=86400
EITOHFORGE_IDEMPOTENCY_WRITE_METHODS=POST,PUT,PATCH,DELETE
EITOHFORGE_IDEMPOTENCY_MAX_BODY_BYTES=1048576
EITOHFORGE_REQUEST_SIGNING_ENABLED=false
EITOHFORGE_REQUEST_SIGNING_SHARED_SECRET=replace-with-request-signing-secret
EITOHFORGE_REQUEST_SIGNING_SIGNATURE_HEADER=x-signature
EITOHFORGE_REQUEST_SIGNING_TIMESTAMP_HEADER=x-signature-timestamp
EITOHFORGE_REQUEST_SIGNING_NONCE_HEADER=x-signature-nonce
EITOHFORGE_REQUEST_SIGNING_KEY_ID_HEADER=x-signature-key-id
EITOHFORGE_REQUEST_SIGNING_DEFAULT_KEY_ID=default
EITOHFORGE_REQUEST_SIGNING_ALLOWED_SKEW_SECONDS=300
EITOHFORGE_REQUEST_SIGNING_NONCE_TTL_SECONDS=300
EITOHFORGE_REQUEST_SIGNING_METHODS=POST,PUT,PATCH,DELETE
EITOHFORGE_REQUEST_SIGNING_SCOPE_PATH_PREFIX=
{% if forge_profile == "minimal" %}
EITOHFORGE_OBSERVABILITY_ENABLED=false
EITOHFORGE_OBSERVABILITY_ENABLE_METRICS=false
EITOHFORGE_OBSERVABILITY_ENABLE_LOGGING=false
EITOHFORGE_OBSERVABILITY_ENABLE_TRACING=false
{% else %}
EITOHFORGE_OBSERVABILITY_ENABLED=true
EITOHFORGE_OBSERVABILITY_ENABLE_METRICS=true
EITOHFORGE_OBSERVABILITY_ENABLE_LOGGING=true
EITOHFORGE_OBSERVABILITY_ENABLE_TRACING=true
{% endif %}
EITOHFORGE_OBSERVABILITY_TRACE_HEADER=x-trace-id
EITOHFORGE_OBSERVABILITY_REQUEST_ID_HEADER=x-request-id
{% if forge_profile == "minimal" %}
EITOHFORGE_AUDIT_ENABLED=false
{% else %}
EITOHFORGE_AUDIT_ENABLED=true
{% endif %}
EITOHFORGE_AUDIT_METHODS=POST,PUT,PATCH,DELETE
EITOHFORGE_AUDIT_SCOPE_PATH_PREFIX=
EITOHFORGE_SEARCH_ENABLED=false
EITOHFORGE_SEARCH_PROVIDER=memory
EITOHFORGE_SEARCH_HOSTS=http://localhost:9200
EITOHFORGE_SEARCH_INDEX_PREFIX={{ package_name }}
EITOHFORGE_SEARCH_USERNAME=
EITOHFORGE_SEARCH_PASSWORD=
EITOHFORGE_SEARCH_VERIFY_TLS=true
{% if forge_profile == "minimal" %}
EITOHFORGE_TENANT_ENABLED=false
EITOHFORGE_TENANT_REQUIRED_FOR_WRITE_METHODS=false
{% else %}
EITOHFORGE_TENANT_ENABLED=true
EITOHFORGE_TENANT_REQUIRED_FOR_WRITE_METHODS=true
{% endif %}
EITOHFORGE_TENANT_WRITE_METHODS=POST,PUT,PATCH,DELETE
EITOHFORGE_TENANT_SCOPE_PATH_PREFIX=
EITOHFORGE_TENANT_RESOURCE_TENANT_HEADER=x-resource-tenant-id
# Optional per-tenant Postgres schema isolation (`search_path`) for SQL databases.
EITOHFORGE_TENANT_DB_SCHEMA_ISOLATION_ENABLED=false
EITOHFORGE_TENANT_DB_SCHEMA_NAME_TEMPLATE={tenant_id}
{% if forge_profile == "minimal" %}
EITOHFORGE_PLUGIN_ENABLED=false
EITOHFORGE_FEATURE_FLAGS_ENABLED=false
{% else %}
EITOHFORGE_PLUGIN_ENABLED=true
EITOHFORGE_FEATURE_FLAGS_ENABLED=true
{% endif %}
EITOHFORGE_FEATURE_FLAGS_ENDPOINT_PATH=/sdk/feature-flags
EITOHFORGE_SECURITY_HARDENING_ENABLED=true
EITOHFORGE_SECURITY_HARDENING_MAX_REQUEST_BYTES=2097152
EITOHFORGE_SECURITY_HARDENING_ALLOWED_HOSTS=*
EITOHFORGE_SECURITY_HARDENING_ADD_SECURITY_HEADERS=true
EITOHFORGE_STORAGE_PROVIDER=local
EITOHFORGE_STORAGE_BUCKET_NAME={{ package_name }}-local-bucket
EITOHFORGE_STORAGE_REGION=us-east-1
EITOHFORGE_STORAGE_ENDPOINT_URL=
EITOHFORGE_STORAGE_AWS_ACCESS_KEY_ID=
EITOHFORGE_STORAGE_AWS_SECRET_ACCESS_KEY=
EITOHFORGE_STORAGE_AWS_SESSION_TOKEN=
EITOHFORGE_STORAGE_PRESIGN_EXPIRES_SECONDS=900
EITOHFORGE_STORAGE_PUBLIC_BASE_URL=
EITOHFORGE_STORAGE_CDN_BASE_URL=
EITOHFORGE_SECRET_PROVIDER=env
EITOHFORGE_SECRET_VAULT_MOUNT=secret
""",
    "forge.dev.json": """{
  "schema_version": 1,
  "default_host": "127.0.0.1",
  "services": [
    {
      "name": "api",
      "module": "{{ package_name }}.main:app",
      "port": 8000
    }
  ]
}
""",
    "app/__init__.py": "",
    "app/main.py": """from fastapi import FastAPI

from app.core.capabilities import register_capabilities_endpoint
from app.core.config import get_settings
from app.core.feature_flags import register_feature_flags_endpoint
from app.core.middleware import register_middleware
from app.core.versioning import ApiVersion, register_versioned_routers
from app.presentation.routers.realtime import register_socket_state, router as realtime_router
from app.presentation.routers.v1.admin import router as v1_admin_router
from app.presentation.routers.v1.health import router as v1_health_router
from app.presentation.routers.v1.tenant import router as v1_tenant_router
from app.presentation.routers.v2.health import router as v2_health_router
from app.presentation.routers.health import router as health_router


def create_app() -> FastAPI:
    app = FastAPI(title="{{ project_name }}")
    register_middleware(app)
    register_capabilities_endpoint(app)
    register_feature_flags_endpoint(app)
    register_versioned_routers(
        app,
        {
            ApiVersion.V1: (v1_health_router, v1_admin_router, v1_tenant_router),
            ApiVersion.V2: (v2_health_router,),
        },
    )
    app.include_router(health_router)
    if get_settings().realtime.enabled:
        register_socket_state(app)
        app.include_router(realtime_router)
    return app


app = create_app()
""",
    **CORE_FILE_TEMPLATES,
    "app/domain/__init__.py": """from app.domain.value_objects import (
    CorrelationId,
    DateTimeRange,
    DomainInvariantError,
    EmailAddress,
    EntityId,
    TenantId,
)
""",
    "app/domain/entities/__init__.py": "",
    "app/domain/value_objects/__init__.py": """from app.domain.value_objects.contact import EmailAddress
from app.domain.value_objects.errors import DomainInvariantError
from app.domain.value_objects.identifiers import CorrelationId, EntityId, TenantId
from app.domain.value_objects.time import DateTimeRange
""",
    "app/domain/value_objects/errors.py": """class DomainInvariantError(ValueError):
    pass
""",
    "app/domain/value_objects/identifiers.py": """from dataclasses import dataclass
import re
from uuid import UUID

from app.domain.value_objects.errors import DomainInvariantError

_ID_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_\\-:.]{1,127}$")
_TENANT_PATTERN = re.compile(r"^[a-z0-9][a-z0-9_\\-]{1,63}$")


@dataclass(frozen=True)
class EntityId:
    value: str

    def __post_init__(self) -> None:
        if not _ID_PATTERN.fullmatch(self.value):
            raise DomainInvariantError("EntityId has invalid format.")


@dataclass(frozen=True)
class TenantId:
    value: str

    def __post_init__(self) -> None:
        if not _TENANT_PATTERN.fullmatch(self.value):
            raise DomainInvariantError("TenantId has invalid format.")


@dataclass(frozen=True)
class CorrelationId:
    value: str

    def __post_init__(self) -> None:
        try:
            UUID(self.value)
        except Exception as exc:
            raise DomainInvariantError("CorrelationId must be a valid UUID.") from exc
""",
    "app/domain/value_objects/contact.py": """from dataclasses import dataclass
import re

from app.domain.value_objects.errors import DomainInvariantError

_EMAIL_PATTERN = re.compile(r"^[A-Za-z0-9._%+\\-]+@[A-Za-z0-9.\\-]+\\.[A-Za-z]{2,}$")


@dataclass(frozen=True)
class EmailAddress:
    value: str

    def __post_init__(self) -> None:
        normalized = self.value.strip().lower()
        if not _EMAIL_PATTERN.fullmatch(normalized):
            raise DomainInvariantError("EmailAddress must be a valid email format.")
        object.__setattr__(self, "value", normalized)
""",
    "app/domain/value_objects/time.py": """from dataclasses import dataclass
from datetime import datetime

from app.domain.value_objects.errors import DomainInvariantError


@dataclass(frozen=True)
class DateTimeRange:
    start: datetime
    end: datetime

    def __post_init__(self) -> None:
        if self.start > self.end:
            raise DomainInvariantError("DateTimeRange requires start <= end.")
""",
    "app/domain/repositories/__init__.py": "",
    "app/domain/repositories/contracts.py": """from __future__ import annotations

from dataclasses import dataclass
from typing import Generic, Protocol, TypeVar, runtime_checkable

from app.application.dto.repository import QuerySpec, RepositoryContext


TEntity = TypeVar("TEntity", covariant=True)
TCreate = TypeVar("TCreate", contravariant=True)
TUpdate = TypeVar("TUpdate", contravariant=True)


@dataclass(frozen=True)
class PageResult(Generic[TEntity]):
    items: tuple[TEntity, ...]
    total: int
    page_size: int
    next_cursor: str | None = None


@runtime_checkable
class RepositoryContract(Protocol, Generic[TEntity, TCreate, TUpdate]):
    async def create(self, payload: TCreate, context: RepositoryContext | None = None) -> TEntity:
        ...

    async def get(self, entity_id: str, context: RepositoryContext | None = None) -> TEntity | None:
        ...

    async def update(
        self, entity_id: str, payload: TUpdate, context: RepositoryContext | None = None
    ) -> TEntity | None:
        ...

    async def delete(self, entity_id: str, context: RepositoryContext | None = None) -> bool:
        ...

    async def list(self, query: QuerySpec, context: RepositoryContext | None = None) -> tuple[TEntity, ...]:
        ...

    async def paginate(
        self, query: QuerySpec, context: RepositoryContext | None = None
    ) -> PageResult[TEntity]:
        ...

    async def bulk_create(
        self, payloads: tuple[TCreate, ...], context: RepositoryContext | None = None
    ) -> tuple[TEntity, ...]:
        ...
""",
    "app/domain/specifications/__init__.py": "",
    **APPLICATION_FILE_TEMPLATES,
    "app/infrastructure/__init__.py": "",
    "app/infrastructure/database/__init__.py": "",
    "app/infrastructure/database/provider.py": """from __future__ import annotations

import importlib
import sqlite3
from dataclasses import dataclass
from typing import Any, Protocol

from app.core.config import DatabaseSettings


class DatabaseProvider(Protocol):
    name: str

    def dsn(self) -> str:
        ...

    def connect(self) -> Any:
        ...

    def ping(self) -> bool:
        ...


@dataclass
class PostgresProvider:
    settings: DatabaseSettings
    connect_timeout_seconds: int = 5
    name: str = "postgres"

    def dsn(self) -> str:
        return self.settings.sqlalchemy_url

    def connect(self) -> Any:
        psycopg = self._load_psycopg()
        db = self.settings
        return psycopg.connect(
            host=db.host,
            port=db.port,
            user=db.username,
            password=db.password,
            dbname=db.name,
            connect_timeout=self.connect_timeout_seconds,
        )

    def ping(self) -> bool:
        try:
            connection = self.connect()
            cursor = connection.cursor()
            cursor.execute("SELECT 1")
            cursor.close()
            connection.close()
        except Exception:
            return False
        return True

    @staticmethod
    def _load_psycopg() -> Any:
        try:
            return importlib.import_module("psycopg")
        except ModuleNotFoundError as exc:
            raise RuntimeError(
                "Postgres provider requires 'psycopg'. Install it with: pip install psycopg[binary]"
            ) from exc


@dataclass
class MySQLProvider:
    settings: DatabaseSettings
    connect_timeout_seconds: int = 5
    name: str = "mysql"

    def dsn(self) -> str:
        return self.settings.sqlalchemy_url

    def connect(self) -> Any:
        pymysql = self._load_pymysql()
        db = self.settings
        return pymysql.connect(
            host=db.host,
            port=db.port,
            user=db.username,
            password=db.password,
            database=db.name,
            connect_timeout=self.connect_timeout_seconds,
        )

    def ping(self) -> bool:
        try:
            connection = self.connect()
            try:
                cursor = connection.cursor()
                cursor.execute("SELECT 1")
                cursor.close()
            finally:
                connection.close()
        except Exception:
            return False
        return True

    @staticmethod
    def _load_pymysql() -> Any:
        try:
            return importlib.import_module("pymysql")
        except ModuleNotFoundError as exc:
            raise RuntimeError(
                "MySQL provider requires 'pymysql'. Install it with: pip install pymysql"
            ) from exc


@dataclass
class SqliteProvider:
    settings: DatabaseSettings
    name: str = "sqlite"

    def dsn(self) -> str:
        return self.settings.sqlalchemy_url

    def connect(self) -> sqlite3.Connection:
        db = self.settings.name.strip()
        if db == ":memory:":
            return sqlite3.connect(":memory:")
        return sqlite3.connect(db)

    def ping(self) -> bool:
        try:
            connection = self.connect()
            try:
                connection.execute("SELECT 1").fetchone()
            finally:
                connection.close()
        except Exception:
            return False
        return True
""",
    "app/infrastructure/database/registry.py": """from __future__ import annotations

from dataclasses import dataclass, field

from app.infrastructure.database.provider import DatabaseProvider


@dataclass
class DatabaseRegistry:
    _providers: dict[str, DatabaseProvider] = field(default_factory=dict)

    def register(self, role: str, provider: DatabaseProvider) -> None:
        self._providers[role] = provider

    def get(self, role: str) -> DatabaseProvider:
        if role not in self._providers:
            raise KeyError(f"No database provider registered for role: {role}")
        return self._providers[role]

    def has(self, role: str) -> bool:
        return role in self._providers
""",
    "app/infrastructure/database/factory.py": """from app.core.config import AppSettings
from app.infrastructure.database.provider import (
    DatabaseProvider,
    MySQLProvider,
    PostgresProvider,
    SqliteProvider,
)
from app.infrastructure.database.registry import DatabaseRegistry


def build_database_provider(settings: AppSettings) -> DatabaseProvider:
    driver = settings.database.driver.lower()
    if driver.startswith("postgresql"):
        return PostgresProvider(settings=settings.database)
    if driver.startswith("mysql"):
        return MySQLProvider(settings=settings.database)
    if driver.startswith("sqlite"):
        return SqliteProvider(settings=settings.database)
    raise ValueError(f"Unsupported database driver: {settings.database.driver}")


def _build_provider_from_role(settings: AppSettings, role: str) -> DatabaseProvider:
    if role == "analytics":
        driver = settings.database_analytics.driver.lower()
        if driver.startswith("postgresql"):
            return PostgresProvider(settings=settings.database_analytics)
        if driver.startswith("mysql"):
            return MySQLProvider(settings=settings.database_analytics)
        if driver.startswith("sqlite"):
            return SqliteProvider(settings=settings.database_analytics)
        raise ValueError(f"Unsupported analytics database driver: {settings.database_analytics.driver}")
    if role == "search":
        driver = settings.database_search.driver.lower()
        if driver.startswith("postgresql"):
            return PostgresProvider(settings=settings.database_search)
        if driver.startswith("mysql"):
            return MySQLProvider(settings=settings.database_search)
        if driver.startswith("sqlite"):
            return SqliteProvider(settings=settings.database_search)
        raise ValueError(f"Unsupported search database driver: {settings.database_search.driver}")
    raise ValueError(f"Unsupported database role: {role}")


def build_database_registry(settings: AppSettings) -> DatabaseRegistry:
    registry = DatabaseRegistry()
    registry.register("primary", build_database_provider(settings))
    if settings.database_analytics.enabled:
        registry.register("analytics", _build_provider_from_role(settings, "analytics"))
    if settings.database_search.enabled:
        registry.register("search", _build_provider_from_role(settings, "search"))
    return registry
""",
    "app/infrastructure/database/transaction.py": """from __future__ import annotations

from collections.abc import Callable, Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from typing import TypeVar

from sqlalchemy.orm import Session, sessionmaker


TResult = TypeVar("TResult")


@dataclass
class UnitOfWork:
    session: Session
    rollback_only: bool = False

    def mark_rollback(self) -> None:
        self.rollback_only = True


class TransactionManager:
    def __init__(self, session_factory: sessionmaker[Session]) -> None:
        self._session_factory = session_factory

    @contextmanager
    def unit_of_work(self) -> Iterator[UnitOfWork]:
        with self._session_factory() as session:
            uow = UnitOfWork(session=session)
            try:
                yield uow
                if uow.rollback_only:
                    session.rollback()
                else:
                    session.commit()
            except Exception:
                session.rollback()
                raise

    def run_in_transaction(self, operation: Callable[[Session], TResult]) -> TResult:
        with self.unit_of_work() as uow:
            return operation(uow.session)
""",
    "app/infrastructure/database/models.py": """from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    pass
""",
    **CACHE_FILE_TEMPLATES,
    "app/infrastructure/repositories/__init__.py": "",
    "app/infrastructure/repositories/sqlalchemy_repository.py": """from __future__ import annotations

import re
from collections.abc import Sequence
from dataclasses import asdict, is_dataclass
from datetime import datetime
from typing import Any, Callable, Generic, Mapping, TypeVar
from uuid import uuid4

from sqlalchemy import Select, func, inspect, select, text
from sqlalchemy.orm import Session, sessionmaker

from app.application.dto.repository import PaginationMode, QuerySpec, RepositoryContext, SortDirection, SortSpec
from app.core.config import get_settings
from app.core.tenant import TenantContext
from app.domain.repositories.contracts import PageResult, RepositoryContract


TEntity = TypeVar("TEntity")
TCreate = TypeVar("TCreate")
TUpdate = TypeVar("TUpdate")


class SQLAlchemyRepository(
    Generic[TEntity, TCreate, TUpdate], RepositoryContract[TEntity, TCreate, TUpdate]
):
    _SCHEMA_NAME_RE = re.compile(r"^[A-Za-z0-9_-]+$")

    def __init__(
        self,
        *,
        session_factory: sessionmaker[Session],
        model_type: type[Any],
        to_entity: Callable[[Any], TEntity],
        create_to_values: Callable[[TCreate], dict[str, Any]] | None = None,
        update_to_values: Callable[[TUpdate], dict[str, Any]] | None = None,
        id_field: str = "id",
    ) -> None:
        self._session_factory = session_factory
        self._model_type = model_type
        self._to_entity = to_entity
        self._create_to_values = create_to_values or self._payload_to_values
        self._update_to_values = update_to_values or self._payload_to_values
        self._id_field = id_field
        self._columns = set(inspect(self._model_type).columns.keys())
        settings = get_settings()
        self._tenant_schema_isolation_enabled = settings.tenant.db_schema_isolation_enabled
        self._tenant_schema_name_template = settings.tenant.db_schema_name_template

    async def create(self, payload: TCreate, context: RepositoryContext | None = None) -> TEntity:
        values = self._create_to_values(payload)
        values = self._apply_write_context(values, context, is_create=True)
        if self._id_field in self._columns and self._id_field not in values:
            values[self._id_field] = str(uuid4())
        with self._session_factory() as session:
            self._apply_tenant_schema_isolation(session, context)
            model = self._model_type(**values)
            session.add(model)
            session.commit()
            session.refresh(model)
            return self._to_entity(model)

    async def get(self, entity_id: str, context: RepositoryContext | None = None) -> TEntity | None:
        with self._session_factory() as session:
            self._apply_tenant_schema_isolation(session, context)
            statement = self._base_statement(context).where(
                getattr(self._model_type, self._id_field) == entity_id
            )
            model = session.scalar(statement)
            if model is None:
                return None
            return self._to_entity(model)

    async def update(
        self, entity_id: str, payload: TUpdate, context: RepositoryContext | None = None
    ) -> TEntity | None:
        values = self._update_to_values(payload)
        values = self._apply_write_context(values, context, is_create=False)
        with self._session_factory() as session:
            self._apply_tenant_schema_isolation(session, context)
            statement = self._base_statement(context).where(
                getattr(self._model_type, self._id_field) == entity_id
            )
            model = session.scalar(statement)
            if model is None:
                return None
            for key, value in values.items():
                if key in self._columns:
                    setattr(model, key, value)
            session.commit()
            session.refresh(model)
            return self._to_entity(model)

    async def delete(self, entity_id: str, context: RepositoryContext | None = None) -> bool:
        with self._session_factory() as session:
            self._apply_tenant_schema_isolation(session, context)
            statement = self._base_statement(context).where(
                getattr(self._model_type, self._id_field) == entity_id
            )
            model = session.scalar(statement)
            if model is None:
                return False
            session.delete(model)
            session.commit()
            return True

    async def list(
        self, query: QuerySpec, context: RepositoryContext | None = None
    ) -> tuple[TEntity, ...]:
        with self._session_factory() as session:
            self._apply_tenant_schema_isolation(session, context)
            statement = self._apply_query(self._base_statement(context), query)
            statement = self._apply_pagination(statement, query)
            models = session.scalars(statement).all()
            return tuple(self._to_entity(model) for model in models)

    async def paginate(
        self, query: QuerySpec, context: RepositoryContext | None = None
    ) -> PageResult[TEntity]:
        with self._session_factory() as session:
            self._apply_tenant_schema_isolation(session, context)
            base_statement = self._base_statement(context)
            count_statement = select(func.count()).select_from(base_statement.subquery())
            total = int(session.scalar(count_statement) or 0)

            statement = self._apply_query(base_statement, query)
            statement = self._apply_pagination(statement, query)
            models = session.scalars(statement).all()
            items = tuple(self._to_entity(model) for model in models)
            next_cursor = self._resolve_next_cursor(models, query, total)
            return PageResult(
                items=items,
                total=total,
                page_size=query.pagination.page_size,
                next_cursor=next_cursor,
            )

    async def bulk_create(
        self, payloads: tuple[TCreate, ...], context: RepositoryContext | None = None
    ) -> tuple[TEntity, ...]:
        with self._session_factory() as session:
            self._apply_tenant_schema_isolation(session, context)
            models: list[Any] = []
            for payload in payloads:
                values = self._apply_write_context(self._create_to_values(payload), context, is_create=True)
                if self._id_field in self._columns and self._id_field not in values:
                    values[self._id_field] = str(uuid4())
                model = self._model_type(**values)
                models.append(model)
            session.add_all(models)
            session.commit()
            for model in models:
                session.refresh(model)
            return tuple(self._to_entity(model) for model in models)

    def _resolve_tenant_id_for_scope(self, context: RepositoryContext | None) -> str | None:
        if context is not None and context.tenant_id is not None:
            return context.tenant_id
        return TenantContext.current().tenant_id

    def _apply_tenant_schema_isolation(
        self,
        session: Session,
        context: RepositoryContext | None,
    ) -> None:
        if not self._tenant_schema_isolation_enabled:
            return

        tenant_id = self._resolve_tenant_id_for_scope(context)
        if tenant_id is None:
            return

        bind = session.get_bind()
        dialect_name = getattr(getattr(bind, "dialect", None), "name", None)
        if dialect_name not in {"postgresql"}:
            return

        schema_name = self._tenant_schema_name_template.format(tenant_id=str(tenant_id).strip())
        if not self._SCHEMA_NAME_RE.match(schema_name):
            raise ValueError(f"Invalid tenant schema name resolved from tenant_id={tenant_id!r}.")

        session.execute(f'SET LOCAL search_path TO "{schema_name}"')

    def _base_statement(self, context: RepositoryContext | None) -> Select[Any]:
        statement = select(self._model_type)
        tenant_id = context.tenant_id if context is not None and context.tenant_id is not None else TenantContext.current().tenant_id
        if tenant_id is not None and "tenant_id" in self._columns:
            statement = statement.where(getattr(self._model_type, "tenant_id") == tenant_id)
        return statement

    def _apply_query(self, statement: Select[Any], query: QuerySpec) -> Select[Any]:
        for condition in query.filters:
            if condition.field not in self._columns:
                continue
            column = getattr(self._model_type, condition.field)
            operator = condition.operator.value
            if operator == "eq":
                statement = statement.where(column == condition.value)
            elif operator == "ne":
                statement = statement.where(column != condition.value)
            elif operator == "gt":
                statement = statement.where(column > condition.value)
            elif operator == "gte":
                statement = statement.where(column >= condition.value)
            elif operator == "lt":
                statement = statement.where(column < condition.value)
            elif operator == "lte":
                statement = statement.where(column <= condition.value)
            elif operator == "contains":
                statement = statement.where(column.contains(condition.value))
            elif operator == "startswith":
                statement = statement.where(column.startswith(condition.value))
            elif operator == "endswith":
                statement = statement.where(column.endswith(condition.value))
            elif operator == "between":
                bounds = self._extract_between_bounds(condition.value)
                if bounds is not None:
                    statement = statement.where(column.between(bounds[0], bounds[1]))
            elif operator == "in":
                values = self._extract_in_values(condition.value)
                if values is not None:
                    statement = statement.where(column.in_(values))
            elif operator == "not_in":
                values = self._extract_in_values(condition.value)
                if values is not None:
                    statement = statement.where(column.not_in(values))
            elif operator == "exists":
                if bool(condition.value):
                    statement = statement.where(column.is_not(None))
                else:
                    statement = statement.where(column.is_(None))

        for sort in query.sorts:
            if sort.field not in self._columns:
                continue
            column = getattr(self._model_type, sort.field)
            statement = statement.order_by(column.asc() if sort.direction.value == "asc" else column.desc())
        return statement

    def _apply_write_context(
        self, values: dict[str, Any], context: RepositoryContext | None, *, is_create: bool
    ) -> dict[str, Any]:
        scoped = dict(values)
        tenant_id = context.tenant_id if context is not None and context.tenant_id is not None else TenantContext.current().tenant_id
        actor_id = context.actor_id if context is not None and context.actor_id is not None else TenantContext.current().actor_id
        if tenant_id is not None and "tenant_id" in self._columns and "tenant_id" not in scoped:
            scoped["tenant_id"] = tenant_id
        if actor_id is not None:
            if is_create and "created_by" in self._columns and "created_by" not in scoped:
                scoped["created_by"] = actor_id
            if "updated_by" in self._columns:
                scoped["updated_by"] = actor_id
        return scoped

    @staticmethod
    def _payload_to_values(payload: Any) -> dict[str, Any]:
        if isinstance(payload, Mapping):
            return dict(payload)
        if hasattr(payload, "model_dump"):
            return dict(payload.model_dump())
        if is_dataclass(payload) and not isinstance(payload, type):
            return dict(asdict(payload))
        if hasattr(payload, "__dict__"):
            return {key: value for key, value in vars(payload).items() if not key.startswith("_")}
        raise TypeError(f"Unsupported payload type: {type(payload)}")

    @staticmethod
    def _extract_between_bounds(value: Any) -> tuple[Any, Any] | None:
        if isinstance(value, Sequence) and not isinstance(value, (str, bytes)) and len(value) == 2:
            return (value[0], value[1])
        return None

    @staticmethod
    def _extract_in_values(value: Any) -> tuple[Any, ...] | None:
        if isinstance(value, Sequence) and not isinstance(value, (str, bytes)):
            return tuple(value)
        return None

    def _apply_pagination(self, statement: Select[Any], query: QuerySpec) -> Select[Any]:
        mode = query.pagination.mode
        if mode == PaginationMode.KEYSET:
            return self._apply_keyset_pagination(statement, query)

        offset = self._resolve_offset(query)
        return statement.offset(offset).limit(query.pagination.page_size)

    def _apply_keyset_pagination(self, statement: Select[Any], query: QuerySpec) -> Select[Any]:
        sort = self._get_primary_sort(query)
        if sort is None:
            return statement.limit(query.pagination.page_size)

        column = getattr(self._model_type, sort.field)
        cursor_value = query.pagination.cursor
        if cursor_value is not None:
            normalized = self._normalize_cursor_value(column, cursor_value)
            if sort.direction.value == "asc":
                statement = statement.where(column > normalized)
            else:
                statement = statement.where(column < normalized)
        return statement.limit(query.pagination.page_size)

    def _resolve_next_cursor(self, models: Sequence[Any], query: QuerySpec, total: int) -> str | None:
        if not models:
            return None
        mode = query.pagination.mode
        if mode == PaginationMode.KEYSET:
            sort = self._get_primary_sort(query)
            if sort is None:
                return None
            last_value = getattr(models[-1], sort.field, None)
            if last_value is None:
                return None
            return str(last_value)

        offset = self._resolve_offset(query)
        next_offset = offset + query.pagination.page_size
        return str(next_offset) if next_offset < total else None

    def _get_primary_sort(self, query: QuerySpec) -> SortSpec | None:
        if query.sorts:
            sort = query.sorts[0]
            if sort.field in self._columns:
                return sort
        if self._id_field in self._columns:
            return SortSpec(field=self._id_field, direction=SortDirection.ASC)
        return None

    @staticmethod
    def _resolve_offset(query: QuerySpec) -> int:
        cursor = query.pagination.cursor
        if query.pagination.mode == PaginationMode.CURSOR and cursor is not None and cursor.isdigit():
            return int(cursor)
        return query.pagination.offset

    @staticmethod
    def _normalize_cursor_value(column: Any, cursor: str) -> Any:
        try:
            python_type = column.type.python_type
        except Exception:
            return cursor

        if python_type is int:
            return int(cursor)
        if python_type is float:
            return float(cursor)
        if python_type is bool:
            return cursor.lower() in {"1", "true", "yes"}
        if python_type is datetime:
            return datetime.fromisoformat(cursor)
        return cursor
""",
    "app/infrastructure/transactions/__init__.py": "",
    "app/infrastructure/transactions/saga.py": """from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Protocol
from uuid import uuid4


class SagaStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    COMPENSATED = "compensated"


@dataclass
class SagaContext:
    saga_id: str = field(default_factory=lambda: str(uuid4()))
    trace_id: str | None = None
    tenant_id: str | None = None
    data: dict[str, Any] = field(default_factory=dict)


class SagaStep(Protocol):
    name: str

    async def execute(self, context: SagaContext) -> None:
        ...

    async def compensate(self, context: SagaContext) -> None:
        ...


class SagaStateStore(Protocol):
    def start(self, saga_name: str, context: SagaContext) -> None:
        ...

    def step_executed(self, saga_name: str, context: SagaContext, step_name: str) -> None:
        ...

    def step_compensated(self, saga_name: str, context: SagaContext, step_name: str) -> None:
        ...

    def finish(self, saga_name: str, context: SagaContext, status: SagaStatus) -> None:
        ...


@dataclass
class InMemorySagaStateStore:
    events: list[tuple[str, str, str, str]] = field(default_factory=list)

    def start(self, saga_name: str, context: SagaContext) -> None:
        self.events.append((saga_name, context.saga_id, "start", SagaStatus.RUNNING.value))

    def step_executed(self, saga_name: str, context: SagaContext, step_name: str) -> None:
        self.events.append((saga_name, context.saga_id, "step", f"executed:{step_name}"))

    def step_compensated(self, saga_name: str, context: SagaContext, step_name: str) -> None:
        self.events.append((saga_name, context.saga_id, "step", f"compensated:{step_name}"))

    def finish(self, saga_name: str, context: SagaContext, status: SagaStatus) -> None:
        self.events.append((saga_name, context.saga_id, "finish", status.value))


@dataclass(frozen=True)
class SagaExecutionResult:
    status: SagaStatus
    executed_steps: tuple[str, ...]
    compensated_steps: tuple[str, ...]
    error_message: str | None = None


class SagaOrchestrator:
    def __init__(self, state_store: SagaStateStore | None = None) -> None:
        self._state_store = state_store or InMemorySagaStateStore()

    async def run(
        self, saga_name: str, steps: tuple[SagaStep, ...], context: SagaContext | None = None
    ) -> SagaExecutionResult:
        saga_context = context or SagaContext()
        executed_steps: list[SagaStep] = []
        compensated_names: list[str] = []
        self._state_store.start(saga_name, saga_context)

        try:
            for step in steps:
                await step.execute(saga_context)
                executed_steps.append(step)
                self._state_store.step_executed(saga_name, saga_context, step.name)

            self._state_store.finish(saga_name, saga_context, SagaStatus.SUCCEEDED)
            return SagaExecutionResult(
                status=SagaStatus.SUCCEEDED,
                executed_steps=tuple(step.name for step in executed_steps),
                compensated_steps=(),
            )
        except Exception as exc:
            for step in reversed(executed_steps):
                try:
                    await step.compensate(saga_context)
                    compensated_names.append(step.name)
                    self._state_store.step_compensated(saga_name, saga_context, step.name)
                except Exception:
                    continue
            final_status = SagaStatus.COMPENSATED if compensated_names else SagaStatus.FAILED
            self._state_store.finish(saga_name, saga_context, final_status)
            return SagaExecutionResult(
                status=final_status,
                executed_steps=tuple(step.name for step in executed_steps),
                compensated_steps=tuple(compensated_names),
                error_message=str(exc),
            )
""",
    **STORAGE_FILE_TEMPLATES,
    **JOBS_FILE_TEMPLATES,
    **MESSAGING_FILE_TEMPLATES,
    **SEARCH_FILE_TEMPLATES,
    **SOCKET_FILE_TEMPLATES,
    **NOTIFICATION_FILE_TEMPLATES,
    **WEBHOOK_FILE_TEMPLATES,
    **EXTERNAL_API_FILE_TEMPLATES,
    "app/presentation/__init__.py": "",
    "app/presentation/routers/__init__.py": "",
    "app/presentation/routers/health.py": """from fastapi import APIRouter

from app.core.health import get_readiness_payload, get_status_payload

router = APIRouter()

@router.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@router.get("/ready")
def ready() -> dict[str, object]:
    return get_readiness_payload()


@router.get("/status")
def status() -> dict[str, object]:
    return get_status_payload()
""",
    "app/presentation/routers/v1/__init__.py": "",
    "app/presentation/routers/v1/admin.py": """from fastapi import APIRouter, Depends

from app.core.security import SecurityPrincipal, require_roles

router = APIRouter()


@router.get("/admin/ping")
def admin_ping(principal: SecurityPrincipal = Depends(require_roles("admin"))) -> dict[str, str]:
    return {"status": "ok", "role": "admin", "actor": principal.actor_id or "unknown"}
""",
    "app/presentation/routers/v1/tenant.py": """from fastapi import APIRouter, Depends

from app.core.abac import TenantMatchPolicy, require_policies

router = APIRouter()


@router.get("/tenant/{resource_tenant_id}/ping")
def tenant_ping(_: object = Depends(require_policies(TenantMatchPolicy()))) -> dict[str, str]:
    return {"status": "ok", "policy": "tenant_match"}
""",
    "app/presentation/routers/v1/health.py": """from fastapi import APIRouter

router = APIRouter()


@router.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok", "version": "v1"}
""",
    "app/presentation/routers/v2/__init__.py": "",
    "app/presentation/routers/v2/health.py": """from fastapi import APIRouter

router = APIRouter()


@router.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok", "version": "v2"}
""",
    "app/presentation/controllers/__init__.py": "",
    "app/modules/__init__.py": "",
    "app/modules/auth/__init__.py": "",
    "app/modules/users/__init__.py": "",
    "tests/__init__.py": "",
    "tests/test_health.py": """from fastapi.testclient import TestClient

from app.main import app


def test_health_endpoint() -> None:
    client = TestClient(app)
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}
""",
    "tests/test_realtime_ws.py": """from datetime import timedelta

from fastapi.testclient import TestClient
from starlette.websockets import WebSocketDisconnect

from app.core.auth import JwtTokenManager
from app.core.config import get_settings
from app.main import app


def _access_token() -> str:
    s = get_settings()
    mgr = JwtTokenManager(
        secret=s.auth.jwt_secret,
        access_ttl=timedelta(minutes=s.auth.access_token_minutes),
        refresh_ttl=timedelta(days=s.auth.refresh_token_days),
    )
    return mgr.issue_token_pair(subject="ws-tester", tenant_id="tenant-ws").access_token


def test_realtime_ws_handshake_and_ping() -> None:
    client = TestClient(app)
    token = _access_token()
    with client.websocket_connect(f"/realtime/ws?token={token}") as ws:
        hello = ws.receive_json()
        assert hello["type"] == "connected"
        assert hello["actor_id"] == "ws-tester"
        ws.send_json({"type": "ping"})
        assert ws.receive_json() == {"type": "pong"}


def test_realtime_ws_rejects_missing_token() -> None:
    client = TestClient(app)
    try:
        with client.websocket_connect("/realtime/ws"):
            pass
    except WebSocketDisconnect as exc:
        assert exc.code == 1008
    else:
        raise AssertionError("expected disconnect")


def test_realtime_ws_join_broadcast() -> None:
    client = TestClient(app)
    token = _access_token()
    with client.websocket_connect(f"/realtime/ws?token={token}") as a:
        assert a.receive_json()["type"] == "connected"
        with client.websocket_connect(f"/realtime/ws?token={token}") as b:
            assert b.receive_json()["type"] == "connected"
            a.send_json({"type": "join", "room": "room.demo"})
            assert a.receive_json()["type"] == "joined"
            b.send_json({"type": "join", "room": "room.demo"})
            assert b.receive_json()["type"] == "joined"
            a.send_json({"type": "broadcast", "room": "room.demo", "event": "demo.evt", "payload": {"x": 1}})
            got_b = b.receive_json()
            got_a = a.receive_json()
            assert got_b["event"] == "demo.evt"
            assert got_b["payload"] == {"x": 1}
            assert got_a["type"] == "broadcast_result"
            assert got_a["delivered"] == 1
""",
    "alembic.ini": """[alembic]
script_location = migrations
prepend_sys_path = .
sqlalchemy.url = postgresql+psycopg://postgres:postgres@localhost:5432/{{ package_name }}

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
""",
    "migrations/README": "Run Alembic migrations from this directory.\n",
    "migrations/script.py.mako": """\"\"\"${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}
\"\"\"
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision: str = ${repr(up_revision)}
down_revision: Union[str, Sequence[str], None] = ${repr(down_revision)}
branch_labels: Union[str, Sequence[str], None] = ${repr(branch_labels)}
depends_on: Union[str, Sequence[str], None] = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
""",
    "migrations/env.py": """from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.core.config import get_settings
from app.infrastructure.database.models import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

settings = get_settings()
config.set_main_option("sqlalchemy.url", settings.database.sqlalchemy_url)
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section) or {},
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
""",
    "migrations/versions/.gitkeep": "",
}


SDK_PROJECT_FILE_OVERRIDES: dict[str, str] = {
    "pyproject.toml": """[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[project]
name = "{{ package_name }}"
version = "0.1.0"
description = "Generated backend service by EitohForge (SDK-first mode)."
requires-python = ">=3.12"
dependencies = [
  "eitohforge-sdk>=0.1.0",
  "fastapi>=0.116.0",
  "pydantic-settings>=2.10.0",
  "uvicorn>=0.32.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
""",
    "app/core/rate_limit.py": """from eitohforge_sdk.core.rate_limit import (
    InMemoryRateLimiter,
    RateLimitRule,
    register_rate_limiter_middleware,
)
""",
    "app/core/idempotency.py": """from eitohforge_sdk.core.idempotency import (
    IdempotencyRecord,
    IdempotencyRule,
    IdempotencyStore,
    InMemoryIdempotencyStore,
    register_idempotency_middleware,
)
""",
    "app/core/request_signing.py": """from eitohforge_sdk.core.request_signing import (
    InMemoryRequestNonceStore,
    RequestNonceStore,
    RequestSigningRule,
    SignaturePayload,
    compute_request_signature,
    register_request_signing_middleware,
)
""",
    "app/core/observability.py": """from eitohforge_sdk.core.observability import (
    InMemoryMetricsSink,
    MetricsSink,
    ObservabilityRule,
    PrometheusMetricsSink,
    get_request_id,
    get_request_trace_id,
    register_observability_middleware,
    register_prometheus_metrics_endpoint,
)
""",
    "app/core/audit.py": """from eitohforge_sdk.core.audit import (
    AuditEvent,
    AuditRule,
    AuditSink,
    InMemoryAuditSink,
    log_audit_event,
    register_audit_middleware,
)
""",
    "app/core/tenant.py": """from eitohforge_sdk.core.tenant import (
    TenantContext,
    TenantIsolationError,
    TenantIsolationRule,
    assert_tenant_access,
    build_tenant_context_from_headers,
    get_request_tenant_context,
    register_tenant_context_middleware,
)
""",
    "app/core/plugins.py": """from eitohforge_sdk.core.plugins import PluginModule, PluginRegistry
""",
    "app/core/feature_flags.py": """from eitohforge_sdk.core.feature_flags import (
    FeatureFlagDefinition,
    FeatureFlagService,
    FeatureFlagTargetingContext,
    register_feature_flags_endpoint,
)
""",
    "app/core/security_hardening.py": """from eitohforge_sdk.core.security_hardening import (
    SecurityHardeningRule,
    register_security_hardening_middleware,
)
""",
    "app/presentation/routers/realtime.py": """# SDK-first: shared WebSocket router (toggle via EITOHFORGE_REALTIME_* / AUTH_JWT_*).
from __future__ import annotations

from app.core.config import get_settings
from eitohforge_sdk.infrastructure.sockets.realtime_router import (
    attach_in_memory_socket_hub,
    build_realtime_router,
)

router = build_realtime_router(settings_provider=get_settings)
register_socket_state = attach_in_memory_socket_hub
""",
    "app/core/capabilities.py": """from collections.abc import Callable

from fastapi import APIRouter, FastAPI

from eitohforge_sdk.core.capabilities import (
    build_capability_profile as sdk_build_capability_profile,
)
from app.core.config import AppSettings, get_settings


def build_capability_profile(
    settings: AppSettings,
    *,
    api_versions: tuple[str, ...] = ("v1", "v2"),
) -> dict[str, object]:
    return sdk_build_capability_profile(settings, api_versions=api_versions)


def register_capabilities_endpoint(
    app: FastAPI,
    *,
    settings_provider: Callable[[], AppSettings] | None = None,
    api_versions: tuple[str, ...] = ("v1", "v2"),
    path: str = "/sdk/capabilities",
) -> APIRouter:
    router = APIRouter()
    resolved_settings_provider = settings_provider or get_settings

    @router.get(path)
    def sdk_capabilities() -> dict[str, object]:
        return build_capability_profile(resolved_settings_provider(), api_versions=api_versions)

    app.include_router(router)
    return router
""",
    "app/core/middleware.py": """from fastapi import FastAPI

from eitohforge_sdk.core import (
    AuditRule,
    IdempotencyRule,
    ObservabilityRule,
    SecurityHardeningRule,
    TenantIsolationRule,
    RateLimitRule,
    RequestSigningRule,
    build_default_error_registry,
    register_error_handlers,
    register_idempotency_middleware,
    register_audit_middleware,
    register_observability_middleware,
    register_rate_limiter_middleware,
    register_request_signing_middleware,
    register_security_hardening_middleware,
    register_security_context_middleware,
    register_tenant_context_middleware,
)
from app.core.config import get_settings


def register_middleware(app: FastAPI) -> None:
    settings = get_settings()
    if settings.security_hardening.enabled:
        register_security_hardening_middleware(
            app,
            SecurityHardeningRule(
                enabled=settings.security_hardening.enabled,
                max_request_bytes=settings.security_hardening.max_request_bytes,
                allowed_hosts=settings.security_hardening.allowed_hosts_tuple,
                add_security_headers=settings.security_hardening.add_security_headers,
            ),
        )
    if settings.audit.enabled:
        register_audit_middleware(
            app,
            AuditRule(
                enabled=settings.audit.enabled,
                methods=settings.audit.methods_tuple,
                scope_path_prefix=settings.audit.scope_path_prefix,
            ),
        )
    if settings.observability.enabled:
        register_observability_middleware(
            app,
            ObservabilityRule(
                enabled=settings.observability.enabled,
                enable_metrics=settings.observability.enable_metrics,
                enable_logging=settings.observability.enable_logging,
                enable_tracing=settings.observability.enable_tracing,
                trace_header=settings.observability.trace_header,
                request_id_header=settings.observability.request_id_header,
            ),
        )
    if settings.request_signing.enabled:
        register_request_signing_middleware(
            app,
            RequestSigningRule(
                enabled=settings.request_signing.enabled,
                signature_header=settings.request_signing.signature_header,
                timestamp_header=settings.request_signing.timestamp_header,
                nonce_header=settings.request_signing.nonce_header,
                key_id_header=settings.request_signing.key_id_header,
                allowed_skew_seconds=settings.request_signing.allowed_skew_seconds,
                nonce_ttl_seconds=settings.request_signing.nonce_ttl_seconds,
                methods=settings.request_signing.methods_tuple,
                scope_path_prefix=settings.request_signing.scope_path_prefix,
            ),
            resolve_secret=lambda key_id: (
                settings.request_signing.shared_secret
                if key_id in (None, "", settings.request_signing.default_key_id)
                else None
            ),
        )
    if settings.idempotency.enabled:
        register_idempotency_middleware(
            app,
            IdempotencyRule(
                header_name=settings.idempotency.header_name,
                write_methods=settings.idempotency.write_methods_tuple,
                ttl_seconds=settings.idempotency.ttl_seconds,
                max_body_bytes=settings.idempotency.max_body_bytes,
            ),
        )
    if settings.rate_limit.enabled:
        register_rate_limiter_middleware(
            app,
            RateLimitRule(
                max_requests=settings.rate_limit.max_requests,
                window_seconds=settings.rate_limit.window_seconds,
                key_headers=settings.rate_limit.key_headers_tuple,
                scope_path_prefix=settings.rate_limit.scope_path_prefix,
            ),
        )
    if settings.tenant.enabled:
        register_tenant_context_middleware(
            app,
            TenantIsolationRule(
                enabled=settings.tenant.enabled,
                required_for_write_methods=settings.tenant.required_for_write_methods,
                write_methods=settings.tenant.write_methods_tuple,
                scope_path_prefix=settings.tenant.scope_path_prefix,
                resource_tenant_header=settings.tenant.resource_tenant_header,
            ),
        )
    register_security_context_middleware(app)
    register_error_handlers(app, build_default_error_registry())
""",
}


ScaffoldMode = Literal["standalone", "sdk"]


def _resolve_templates(mode: ScaffoldMode) -> dict[str, str]:
    if mode == "sdk":
        return {**PROJECT_FILE_TEMPLATES, **SDK_PROJECT_FILE_OVERRIDES}
    return PROJECT_FILE_TEMPLATES


def build_context(project_name: str, *, forge_profile: str = "standard") -> TemplateContext:
    """Build a rendering context from a project name."""
    package_name = re.sub(r"[^a-zA-Z0-9_]", "_", project_name.lower())
    return TemplateContext(
        project_name=project_name, package_name=package_name, forge_profile=forge_profile
    )


def render_project(project_dir: Path, context: TemplateContext, *, mode: ScaffoldMode = "sdk") -> None:
    """Render all project files to disk."""
    templates = _resolve_templates(mode)
    for relative_path, raw_template in templates.items():
        destination = project_dir / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        content = Template(raw_template).render(
            project_name=context.project_name,
            package_name=context.package_name,
            forge_profile=context.forge_profile,
        )
        destination.write_text(content, encoding="utf-8")

