"""Database migration commands backed by Alembic."""

from __future__ import annotations

from pathlib import Path
import subprocess
import sys

import typer


db_app = typer.Typer(help="Database and migration operations.")


def _run_alembic(args: list[str], project_path: Path, config_path: Path | None = None) -> None:
    command = [sys.executable, "-m", "alembic"]
    if config_path is not None:
        command.extend(["-c", str(config_path)])
    command.extend(args)

    result = subprocess.run(  # noqa: S603
        command,
        cwd=project_path,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.stdout:
        typer.echo(result.stdout.strip())
    if result.stderr:
        typer.echo(result.stderr.strip(), err=True)
    if result.returncode != 0:
        raise typer.Exit(code=result.returncode)


def _resolve_project_context(path: Path, config: str) -> tuple[Path, Path]:
    project_path = path.resolve()
    if not project_path.exists():
        raise typer.BadParameter(f"Project path does not exist: {project_path}")
    config_path = (project_path / config).resolve()
    return project_path, config_path


@db_app.command("init")
def init(
    path: Path = typer.Option(Path("."), "--path", help="Project directory path."),
    config: str = typer.Option("alembic.ini", "--config", help="Alembic config filename."),
) -> None:
    """Initialize migration files for an existing project."""
    project_path, config_path = _resolve_project_context(path, config)
    migrations_path = project_path / "migrations"
    if config_path.exists() and migrations_path.exists():
        typer.echo("Migration scaffolding already exists.")
        return
    _run_alembic(["init", "migrations"], project_path)


@db_app.command("migrate")
def migrate(
    message: str = typer.Option(..., "--message", "-m", help="Migration message."),
    path: Path = typer.Option(Path("."), "--path", help="Project directory path."),
    config: str = typer.Option("alembic.ini", "--config", help="Alembic config filename."),
) -> None:
    """Create an autogenerated migration revision."""
    project_path, config_path = _resolve_project_context(path, config)
    _run_alembic(["revision", "--autogenerate", "-m", message], project_path, config_path)


@db_app.command("upgrade")
def upgrade(
    revision: str = typer.Option("head", "--revision", "-r", help="Revision target."),
    path: Path = typer.Option(Path("."), "--path", help="Project directory path."),
    config: str = typer.Option("alembic.ini", "--config", help="Alembic config filename."),
) -> None:
    """Upgrade database schema to target revision."""
    project_path, config_path = _resolve_project_context(path, config)
    _run_alembic(["upgrade", revision], project_path, config_path)


@db_app.command("downgrade")
def downgrade(
    revision: str = typer.Option("-1", "--revision", "-r", help="Revision target."),
    path: Path = typer.Option(Path("."), "--path", help="Project directory path."),
    config: str = typer.Option("alembic.ini", "--config", help="Alembic config filename."),
) -> None:
    """Downgrade database schema to target revision."""
    project_path, config_path = _resolve_project_context(path, config)
    _run_alembic(["downgrade", revision], project_path, config_path)


@db_app.command("current")
def current(
    path: Path = typer.Option(Path("."), "--path", help="Project directory path."),
    config: str = typer.Option("alembic.ini", "--config", help="Alembic config filename."),
) -> None:
    """Show current database revision."""
    project_path, config_path = _resolve_project_context(path, config)
    _run_alembic(["current"], project_path, config_path)

