"""Authentication primitives."""

from eitohforge_sdk.core.auth.jwt import (
    InMemoryRefreshTokenStore,
    InvalidTokenError,
    JwtTokenError,
    JwtTokenManager,
    RefreshTokenRecord,
    RefreshTokenReplayError,
    RefreshTokenStore,
    TokenExpiredError,
    TokenPair,
    TokenType,
)
from eitohforge_sdk.core.auth.session import (
    InMemorySessionStore,
    RedisSessionStore,
    SessionError,
    SessionExpiredError,
    SessionManager,
    SessionNotFoundError,
    SessionRecord,
    SessionRevokedError,
    SessionStore,
    build_session_store,
)
from eitohforge_sdk.core.auth.sso import (
    ExternalIdentity,
    InMemorySsoLinkStore,
    SsoBroker,
    SsoError,
    SsoIdentityNotLinkedError,
    SsoLinkStore,
    SsoLoginResult,
    SsoProvider,
    SsoProviderNotFoundError,
)
from eitohforge_sdk.core.auth.sso_adapters import (
    OidcExchangeError,
    OidcSsoProvider,
    SamlExchangeError,
    SamlSsoProvider,
    SsoAdapterError,
)

__all__ = [
    "InMemoryRefreshTokenStore",
    "InMemorySessionStore",
    "InvalidTokenError",
    "JwtTokenError",
    "JwtTokenManager",
    "RedisSessionStore",
    "RefreshTokenRecord",
    "RefreshTokenReplayError",
    "RefreshTokenStore",
    "SsoAdapterError",
    "OidcExchangeError",
    "SamlExchangeError",
    "OidcSsoProvider",
    "SamlSsoProvider",
    "SessionError",
    "SessionExpiredError",
    "SessionManager",
    "SessionNotFoundError",
    "SessionRecord",
    "SessionRevokedError",
    "SessionStore",
    "SsoBroker",
    "SsoError",
    "SsoLoginResult",
    "SsoProvider",
    "SsoLinkStore",
    "SsoProviderNotFoundError",
    "SsoIdentityNotLinkedError",
    "ExternalIdentity",
    "InMemorySsoLinkStore",
    "TokenExpiredError",
    "TokenPair",
    "TokenType",
    "build_session_store",
]

