"""Core SDK modules."""

from eitohforge_sdk.core.api_version_deprecation import register_api_version_deprecation_middleware
from eitohforge_sdk.core.api_versioning import ApiVersion, build_versioned_router, register_versioned_routers
from eitohforge_sdk.core.audit import (
    AuditEvent,
    AuditRule,
    AuditSink,
    InMemoryAuditSink,
    log_audit_event,
    register_audit_middleware,
)
from eitohforge_sdk.core.abac import (
    AccessPolicy,
    ActorPresentPolicy,
    PolicyContext,
    PolicyDeniedError,
    PolicyEngine,
    TenantMatchPolicy,
    abac_required,
    attributes_from_request,
    require_policies,
)
from eitohforge_sdk.core.auth import (
    ExternalIdentity,
    InMemoryRefreshTokenStore,
    InMemorySessionStore,
    InMemorySsoLinkStore,
    InvalidTokenError,
    JwtTokenError,
    JwtTokenManager,
    OidcExchangeError,
    OidcSsoProvider,
    RedisSessionStore,
    RefreshTokenRecord,
    RefreshTokenReplayError,
    RefreshTokenStore,
    SessionError,
    SessionExpiredError,
    SessionManager,
    SessionNotFoundError,
    SessionRecord,
    SessionRevokedError,
    SessionStore,
    SamlExchangeError,
    SamlSsoProvider,
    SsoAdapterError,
    SsoBroker,
    SsoError,
    SsoIdentityNotLinkedError,
    SsoLinkStore,
    SsoLoginResult,
    SsoProvider,
    SsoProviderNotFoundError,
    TokenExpiredError,
    TokenPair,
    TokenType,
    build_session_store,
)
from eitohforge_sdk.core.capabilities import (
    CapabilityFeatureFlags,
    build_capability_profile,
    register_capabilities_endpoint,
)
from eitohforge_sdk.core.deployment import EnvironmentBehavior, resolve_environment_behavior
from eitohforge_sdk.core.feature_catalog import (
    FORGE_FEATURE_CATALOG,
    FeatureArea,
    list_feature_catalog,
)
from eitohforge_sdk.core.forge_application import ForgeAppBuildConfig, build_forge_app
from eitohforge_sdk.core.forge_toggles import (
    ForgePlatformToggles,
    default_forge_platform_toggles,
    effective_feature,
    forge_platform_toggles_uniform,
)
from eitohforge_sdk.core.error_middleware import register_error_handlers
from eitohforge_sdk.core.error_registry import ErrorDefinition, ErrorRegistry, build_default_error_registry
from eitohforge_sdk.core.feature_flags import (
    FeatureFlagDefinition,
    FeatureFlagService,
    FeatureFlagTargetingContext,
    register_feature_flags_endpoint,
)
from eitohforge_sdk.core.idempotency import (
    IdempotencyRecord,
    IdempotencyRule,
    InMemoryIdempotencyStore,
    register_idempotency_middleware,
)
from eitohforge_sdk.core.health import HealthCheckResult, register_health_endpoints, run_health_checks
from eitohforge_sdk.core.observability import (
    InMemoryMetricsSink,
    MetricsSink,
    ObservabilityRule,
    PrometheusMetricsSink,
    get_request_id,
    get_request_trace_id,
    register_observability_middleware,
    register_prometheus_metrics_endpoint,
)
from eitohforge_sdk.core.performance import BenchmarkMetric, detect_regressions, run_micro_benchmarks
from eitohforge_sdk.core.rate_limit import InMemoryRateLimiter, RateLimitRule, register_rate_limiter_middleware
from eitohforge_sdk.core.request_signing import (
    InMemoryRequestNonceStore,
    RequestSigningRule,
    SignaturePayload,
    compute_request_signature,
    register_request_signing_middleware,
)
from eitohforge_sdk.core.security import (
    RoleDeniedError,
    SecurityPrincipal,
    assert_roles,
    principal_from_context,
    principal_from_headers,
    rbac_required,
    require_roles,
)
from eitohforge_sdk.core.security_hardening import (
    SecurityHardeningRule,
    register_security_hardening_middleware,
)
from eitohforge_sdk.core.security_context import (
    SecurityContext,
    build_security_context_from_headers,
    get_request_security_context,
    register_security_context_middleware,
)
from eitohforge_sdk.core.tenant import (
    TenantContext,
    TenantIsolationError,
    TenantIsolationRule,
    assert_tenant_access,
    build_tenant_context_from_headers,
    get_request_tenant_context,
    register_tenant_context_middleware,
)
from eitohforge_sdk.core.plugins import PluginModule, PluginRegistry

__all__ = [
    "ApiVersion",
    "AuditEvent",
    "AuditRule",
    "AuditSink",
    "AccessPolicy",
    "ActorPresentPolicy",
    "CapabilityFeatureFlags",
    "EnvironmentBehavior",
    "FeatureArea",
    "FORGE_FEATURE_CATALOG",
    "ForgeAppBuildConfig",
    "ForgePlatformToggles",
    "default_forge_platform_toggles",
    "effective_feature",
    "forge_platform_toggles_uniform",
    "ErrorDefinition",
    "ErrorRegistry",
    "FeatureFlagDefinition",
    "FeatureFlagTargetingContext",
    "FeatureFlagService",
    "InMemoryRefreshTokenStore",
    "InMemorySessionStore",
    "InMemorySsoLinkStore",
    "InMemoryAuditSink",
    "InMemoryIdempotencyStore",
    "InMemoryRequestNonceStore",
    "InvalidTokenError",
    "IdempotencyRecord",
    "IdempotencyRule",
    "HealthCheckResult",
    "JwtTokenError",
    "JwtTokenManager",
    "OidcSsoProvider",
    "OidcExchangeError",
    "InMemoryRateLimiter",
    "InMemoryMetricsSink",
    "PrometheusMetricsSink",
    "PolicyContext",
    "PolicyDeniedError",
    "PolicyEngine",
    "MetricsSink",
    "ObservabilityRule",
    "BenchmarkMetric",
    "RedisSessionStore",
    "RefreshTokenRecord",
    "RefreshTokenReplayError",
    "RefreshTokenStore",
    "RateLimitRule",
    "RequestSigningRule",
    "SessionError",
    "SessionExpiredError",
    "SessionManager",
    "SessionNotFoundError",
    "SessionRecord",
    "SessionRevokedError",
    "SessionStore",
    "SamlSsoProvider",
    "SamlExchangeError",
    "SsoAdapterError",
    "SsoBroker",
    "SsoError",
    "SsoLoginResult",
    "SsoProvider",
    "SsoLinkStore",
    "SsoProviderNotFoundError",
    "SsoIdentityNotLinkedError",
    "ExternalIdentity",
    "SignaturePayload",
    "TenantMatchPolicy",
    "TokenExpiredError",
    "TokenPair",
    "TokenType",
    "RoleDeniedError",
    "SecurityContext",
    "SecurityPrincipal",
    "SecurityHardeningRule",
    "TenantContext",
    "TenantIsolationRule",
    "TenantIsolationError",
    "PluginModule",
    "PluginRegistry",
    "abac_required",
    "attributes_from_request",
    "assert_roles",
    "log_audit_event",
    "build_capability_profile",
    "build_forge_app",
    "build_security_context_from_headers",
    "require_policies",
    "build_session_store",
    "list_feature_catalog",
    "resolve_environment_behavior",
    "build_versioned_router",
    "build_default_error_registry",
    "get_request_security_context",
    "principal_from_context",
    "principal_from_headers",
    "get_request_id",
    "get_request_trace_id",
    "rbac_required",
    "register_capabilities_endpoint",
    "register_audit_middleware",
    "register_api_version_deprecation_middleware",
    "register_versioned_routers",
    "register_idempotency_middleware",
    "register_health_endpoints",
    "register_observability_middleware",
    "register_prometheus_metrics_endpoint",
    "register_request_signing_middleware",
    "register_rate_limiter_middleware",
    "register_security_context_middleware",
    "register_security_hardening_middleware",
    "run_micro_benchmarks",
    "detect_regressions",
    "register_error_handlers",
    "require_roles",
    "run_health_checks",
    "compute_request_signature",
    "register_feature_flags_endpoint",
    "register_tenant_context_middleware",
    "get_request_tenant_context",
    "build_tenant_context_from_headers",
    "assert_tenant_access",
]

